### ISSUE TITLE
Bug: Not able to use Redo functionality 

### ISSUE THREAD

**Issue by Anjan-Gowda** [BharathRavi27/code-ng-switch#4]
In Ubuntu platform unable to use Redo command

**Comment by BharathRavi27** [comment]
Thanks for pointing it out @Anjan-Gowda. I have not tested this on an Ubuntu machine. Could you suggest an alternative key to be used in Ubuntu? `Cmd+Y` was just my convenience.

**Comment by Anjan-Gowda** [comment]
Alternate key would be `ctrl+shift+y` or `ctrl+w`. I believe there's no command with ctrl and w

**Comment by Anjan-Gowda** [comment]
Again 3keys not recommended though 😬

**Comment by BharathRavi27** [comment]
I have changed the key binding for non-mac devices to `Ctrl+Alt+Y`.
If there's a conflict still, I recommend visiting the keyboard shortcuts settings in vs code by searching for **Open Keyboard Shortcuts** from the command panel(`Ctrl+Shift+P`) and searching for `Alt+Ctrl+Y` and resolve the conflict. I will add this in the docs as well @Anjan-Gowda

**Comment by Anjan-Gowda** [comment]
+1
